### ISSUE TITLE
user 엔티티 테이블 제목 변경

### ISSUE THREAD

**Issue by hippo-an** [ejejc/jpaMaster#2]
문제 상황 : hibernate.ddl-auto 속성을 주고 어플리케이션을 구동하는 경우 user 테이블에서 CommandAcceptanceException 발생합니다.

원인 : 엔티티 명으로 설정된 user 라는 테이블은 데이터베이스에 기본적으로 사용하는 테이블인 user 와 겹칩니다. 데이터베이스 메타 테이블인 user 테이블을 삭제하려고 시도하기 때문에 애러가 발생합니다.

개선 : 엔티티 클래스 이름에 's' 를 추가하거나 @Table(name = "users") 어노테이션을 사용해 명시적으로 테이블 명을 변경하는것이 좋을 것 같습니다.

**Comment by ejejc** [comment]
알겠습니다 ~!!! @table(name = "users") 이렇게 써서 수정할께욥!! 👍🏻
